/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { WendButtonVariant } from "./components/wend-button/wend-button";
export { WendButtonVariant } from "./components/wend-button/wend-button";
export namespace Components {
    interface WendButton {
        /**
          * Disables the button.
          * @default false
         */
        "disabled": boolean;
        /**
          * Visual style of the button.
          * @default 'primary'
         */
        "variant": WendButtonVariant;
    }
}
declare global {
    interface HTMLWendButtonElement extends Components.WendButton, HTMLStencilElement {
    }
    var HTMLWendButtonElement: {
        prototype: HTMLWendButtonElement;
        new (): HTMLWendButtonElement;
    };
    interface HTMLElementTagNameMap {
        "wend-button": HTMLWendButtonElement;
    }
}
declare namespace LocalJSX {
    interface WendButton {
        /**
          * Disables the button.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Visual style of the button.
          * @default 'primary'
         */
        "variant"?: WendButtonVariant;
    }

    interface WendButtonAttributes {
        "variant": WendButtonVariant;
        "disabled": boolean;
    }

    interface IntrinsicElements {
        "wend-button": Omit<WendButton, keyof WendButtonAttributes> & { [K in keyof WendButton & keyof WendButtonAttributes]?: WendButton[K] } & { [K in keyof WendButton & keyof WendButtonAttributes as `attr:${K}`]?: WendButtonAttributes[K] } & { [K in keyof WendButton & keyof WendButtonAttributes as `prop:${K}`]?: WendButton[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wend-button": LocalJSX.IntrinsicElements["wend-button"] & JSXBase.HTMLAttributes<HTMLWendButtonElement>;
        }
    }
}
