import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import prettierConfig from 'eslint-config-prettier';
import globals from 'globals';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/www/**',
      '**/.stencil/**',
      '**/loader/**',
      '**/*.d.ts'
    ]
  },
  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: {
          // Root-level tooling configs (e.g. stencil.config.ts) that live outside
          // their package's `rootDir` and so aren't part of any real tsconfig project.
          allowDefaultProject: ['packages/web-components/stencil.config.ts']
        },
        tsconfigRootDir: import.meta.dirname
      }
    }
  },
  // Plain JS config/build files aren't part of any tsconfig `include` — disable
  // type-aware rules for them so typescript-eslint doesn't fail resolving a project.
  {
    files: ['**/*.{js,mjs,cjs}'],
    extends: [tseslint.configs.disableTypeChecked],
    languageOptions: {
      globals: { ...globals.node }
    }
  },
  {
    // CJS config files (postcss.config.js, etc.) — their loaders require module.exports + require().
    files: ['**/*.config.js'],
    rules: {
      '@typescript-eslint/no-require-imports': 'off'
    }
  },
  {
    files: ['packages/design-sync-mcp/src/**/*.ts'],
    languageOptions: {
      globals: { ...globals.node }
    }
  },
  {
    files: ['packages/web-components/src/**/*.{ts,tsx}'],
    languageOptions: {
      globals: { ...globals.browser }
    },
    rules: {
      // Stencil's JSX runtime uses `h` as the pragma; components never import it explicitly.
      '@typescript-eslint/no-unused-vars': ['error', { varsIgnorePattern: '^h$' }],
      // typescript-eslint's type-aware linting doesn't cleanly resolve JSX return types under
      // Stencil's classic (jsxFactory: "h") transform — `tsc --noEmit` reports zero errors here,
      // confirming this is a lint/type-info retrieval gap, not a real correctness issue.
      '@typescript-eslint/no-unsafe-return': 'off'
    }
  },
  {
    // Generated by Stencil's React output target (except index.ts) — they already
    // carry their own `/* eslint-disable */` header; this just quiets ESLint's
    // "unused eslint-disable directive" meta-warning on files with nothing to flag.
    files: ['packages/react/src/*.ts'],
    ignores: ['packages/react/src/index.ts'],
    linterOptions: {
      reportUnusedDisableDirectives: 'off'
    }
  },
  {
    files: ['packages/react/**/*.{ts,tsx}'],
    plugins: { react, 'react-hooks': reactHooks },
    rules: {
      ...react.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off'
    },
    languageOptions: {
      globals: { ...globals.browser }
    },
    settings: {
      react: { version: 'detect' }
    }
  },
  prettierConfig
);
