'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@wend-ui/web-components/dist/components";
import { WendButton as WendButtonElement, defineCustomElement as defineWendButton } from "@wend-ui/web-components/dist/components/wend-button.js";

export type WendButtonEvents = NonNullable<unknown>;

export const WendButton: StencilReactComponent<WendButtonElement, WendButtonEvents, Components.WendButton> = /*@__PURE__*/ createComponent<WendButtonElement, WendButtonEvents, Components.WendButton>({
    tagName: 'wend-button',
    elementClass: WendButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as WendButtonEvents,
    defineCustomElement: defineWendButton
});
